import React from "react";
import { useCurrentFrame } from "remotion";
import { BANDS, COLORS, CONTENT_WIDTH, FONT_FAMILY, SAFE, TYPE, variation } from "../brand";
import metrics from "./caption-metrics.json";
import { measureEm } from "./measure";
import { LINE_CUT } from "./motion";

// The signature caption stack: every line is fitted so its INK spans exactly `width`, short lines
// huge, long lines condensed. Widths are measured in the DOM with the caption axes (wdth 60,
// wght 850); side bearings, ascenders and descenders come from the font itself at the same
// instance (caption-metrics.json, generated by scripts/font_metrics.py), so the first and last
// glyph touch the margins exactly and lines are stacked by their real extents:
//
//   baseline[i+1] = baseline[i] + descent[i] + 0.12 x capHeight + ascent[i+1]
//
// i.e. a 0.12-cap gap between the lowest descender of a line and the tallest ascender of the
// next, so descenders never touch the next line.

type Glyph = [number, number, number, number, number]; // advance, xMin, xMax, yMin, yMax (em)
const GLYPHS = metrics.glyphs as unknown as Record<string, Glyph>;
const FALLBACK: Glyph = [0.45, 0.01, 0.44, -0.24, 0.79]; // conservative: tall and deep
const CAP = metrics.capHeight;
const glyph = (ch: string): Glyph => GLYPHS[ch] ?? FALLBACK;

export type StackLine = { text: string; fontSize: number; x: number; baseline: number; inkWidth: number };
export type StackLayout = { lines: StackLine[]; height: number; width: number };

export type StackOptions = {
  width?: number;
  /** Cap for very short lines ("Captured."), px. */
  maxFontSize?: number;
  /** If the stack is taller than this, every line scales down by the same factor. */
  maxHeight?: number;
  gapRatio?: number;
};

export const layoutStack = (rawLines: string[], opts: StackOptions = {}): StackLayout => {
  const { width = CONTENT_WIDTH, maxFontSize = 240, maxHeight = Infinity, gapRatio = 0.12 } = opts;
  const per = rawLines
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .map((text) => {
      const chars = Array.from(text);
      const first = glyph(chars[0]);
      const last = glyph(chars[chars.length - 1]);
      const lsb = first[1];
      const rsb = last[0] - last[2];
      const ink = measureEm(text, TYPE.caption) - lsb - rsb;
      let asc = 0;
      let desc = 0;
      for (const ch of chars) {
        if (ch === " ") continue;
        const g = glyph(ch);
        asc = Math.max(asc, g[4]);
        desc = Math.max(desc, -g[3]);
      }
      return { text, ink, lsb, asc, desc };
    });
  const build = (sizes: number[]) => {
    const lines: StackLine[] = [];
    let baseline = 0;
    per.forEach((p, i) => {
      const s = sizes[i];
      if (i === 0) baseline = p.asc * s;
      else {
        const prev = per[i - 1];
        const ps = sizes[i - 1];
        baseline += prev.desc * ps + gapRatio * CAP * Math.max(ps, s) + p.asc * s;
      }
      lines.push({ text: p.text, fontSize: s, x: -p.lsb * s, baseline, inkWidth: p.ink * s });
    });
    const lastP = per[per.length - 1];
    const height = per.length ? baseline + lastP.desc * sizes[sizes.length - 1] : 0;
    return { lines, height };
  };
  let sizes = per.map((p) => Math.min(maxFontSize, width / p.ink));
  let out = build(sizes);
  if (out.height > maxHeight) {
    const k = maxHeight / out.height;
    sizes = sizes.map((s) => s * k);
    out = build(sizes);
  }
  return { ...out, width };
};

export type FitStackProps = StackOptions & {
  lines: string[];
  x?: number;
  /** Top edge (anchor "top") or lowest descender (anchor "bottom"). */
  y?: number;
  anchor?: "top" | "bottom";
  /** Frame the first line cuts in; each next line cuts in LINE_CUT frames later. */
  start?: number;
  color?: string;
  layout?: StackLayout;
};

export const FitStack: React.FC<FitStackProps> = ({
  lines,
  x = SAFE.left,
  y = BANDS.captionBottom,
  anchor = "bottom",
  start = 0,
  color = COLORS.ink,
  layout,
  ...opts
}) => {
  const frame = useCurrentFrame();
  const l = layout ?? layoutStack(lines, opts);
  const top = anchor === "bottom" ? y - l.height : y;
  return (
    <svg
      width={l.width}
      height={Math.max(1, l.height)}
      style={{ position: "absolute", left: x, top, overflow: "visible" }}
    >
      {l.lines.map((line, i) =>
        frame >= start + i * LINE_CUT ? (
          <text
            key={i}
            x={line.x}
            y={line.baseline}
            fill={color}
            fontFamily={FONT_FAMILY}
            fontSize={line.fontSize}
            style={{ fontVariationSettings: variation(TYPE.caption) }}
          >
            {line.text}
          </text>
        ) : null,
      )}
    </svg>
  );
};
